
package fr.afcepf.al33.citron.ws.saison.ws;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ServiceClientArticleSaison", targetNamespace = "http://ws.saison.ws.citron.al33.afcepf.fr/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ServiceClientArticleSaison {


    /**
     * 
     * @return
     *     returns java.util.List<fr.afcepf.al33.citron.ws.saison.ws.Article>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listeArticles", targetNamespace = "http://ws.saison.ws.citron.al33.afcepf.fr/", className = "fr.afcepf.al33.citron.ws.saison.ws.ListeArticles")
    @ResponseWrapper(localName = "listeArticlesResponse", targetNamespace = "http://ws.saison.ws.citron.al33.afcepf.fr/", className = "fr.afcepf.al33.citron.ws.saison.ws.ListeArticlesResponse")
    public List<Article> listeArticles();

    /**
     * 
     * @return
     *     returns java.util.List<fr.afcepf.al33.citron.ws.saison.ws.Categorie>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listeCategories", targetNamespace = "http://ws.saison.ws.citron.al33.afcepf.fr/", className = "fr.afcepf.al33.citron.ws.saison.ws.ListeCategories")
    @ResponseWrapper(localName = "listeCategoriesResponse", targetNamespace = "http://ws.saison.ws.citron.al33.afcepf.fr/", className = "fr.afcepf.al33.citron.ws.saison.ws.ListeCategoriesResponse")
    public List<Categorie> listeCategories();

    /**
     * 
     * @param nom
     * @return
     *     returns java.util.List<fr.afcepf.al33.citron.ws.saison.ws.Article>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listeArticlesParNom", targetNamespace = "http://ws.saison.ws.citron.al33.afcepf.fr/", className = "fr.afcepf.al33.citron.ws.saison.ws.ListeArticlesParNom")
    @ResponseWrapper(localName = "listeArticlesParNomResponse", targetNamespace = "http://ws.saison.ws.citron.al33.afcepf.fr/", className = "fr.afcepf.al33.citron.ws.saison.ws.ListeArticlesParNomResponse")
    public List<Article> listeArticlesParNom(
        @WebParam(name = "nom", targetNamespace = "")
        String nom);

    /**
     * 
     * @param categorie
     * @return
     *     returns java.util.List<fr.afcepf.al33.citron.ws.saison.ws.Article>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listeArticlesParCategorie", targetNamespace = "http://ws.saison.ws.citron.al33.afcepf.fr/", className = "fr.afcepf.al33.citron.ws.saison.ws.ListeArticlesParCategorie")
    @ResponseWrapper(localName = "listeArticlesParCategorieResponse", targetNamespace = "http://ws.saison.ws.citron.al33.afcepf.fr/", className = "fr.afcepf.al33.citron.ws.saison.ws.ListeArticlesParCategorieResponse")
    public List<Article> listeArticlesParCategorie(
        @WebParam(name = "categorie", targetNamespace = "")
        Categorie categorie);

    /**
     * 
     * @param mois
     * @return
     *     returns java.util.List<fr.afcepf.al33.citron.ws.saison.ws.Article>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listeArticlesParMois", targetNamespace = "http://ws.saison.ws.citron.al33.afcepf.fr/", className = "fr.afcepf.al33.citron.ws.saison.ws.ListeArticlesParMois")
    @ResponseWrapper(localName = "listeArticlesParMoisResponse", targetNamespace = "http://ws.saison.ws.citron.al33.afcepf.fr/", className = "fr.afcepf.al33.citron.ws.saison.ws.ListeArticlesParMoisResponse")
    public List<Article> listeArticlesParMois(
        @WebParam(name = "mois", targetNamespace = "")
        int mois);

    /**
     * 
     * @param categorie
     * @param mois
     * @return
     *     returns java.util.List<fr.afcepf.al33.citron.ws.saison.ws.Article>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listeArticlesParCategorieEtMois", targetNamespace = "http://ws.saison.ws.citron.al33.afcepf.fr/", className = "fr.afcepf.al33.citron.ws.saison.ws.ListeArticlesParCategorieEtMois")
    @ResponseWrapper(localName = "listeArticlesParCategorieEtMoisResponse", targetNamespace = "http://ws.saison.ws.citron.al33.afcepf.fr/", className = "fr.afcepf.al33.citron.ws.saison.ws.ListeArticlesParCategorieEtMoisResponse")
    public List<Article> listeArticlesParCategorieEtMois(
        @WebParam(name = "categorie", targetNamespace = "")
        Categorie categorie,
        @WebParam(name = "mois", targetNamespace = "")
        int mois);

}
