
package fr.afcepf.al33.citron.ws.saison.ws;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.ResourceBundle;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ServiceClientArticleSaisonImplService", targetNamespace = "http://ws.saison.ws.citron.al33.afcepf.fr/", wsdlLocation = "http://localhost:7878/articlesSaison/service/serviceClientArticleSaison?wsdl")
public class ServiceClientArticleSaisonImplService
    extends Service
{

    private final static URL SERVICECLIENTARTICLESAISONIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException SERVICECLIENTARTICLESAISONIMPLSERVICE_EXCEPTION;
    private final static QName SERVICECLIENTARTICLESAISONIMPLSERVICE_QNAME = new QName("http://ws.saison.ws.citron.al33.afcepf.fr/", "ServiceClientArticleSaisonImplService");    
    
    static {

    	ResourceBundle bundle = ResourceBundle.getBundle("application");
    	String wsHost = bundle.getString("webservice.host");
    	String wsPort = bundle.getString("webservice.port");

    	URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://" + wsHost + ":" + wsPort + "/articlesSaison/service/serviceClientArticleSaison?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SERVICECLIENTARTICLESAISONIMPLSERVICE_WSDL_LOCATION = url;
        SERVICECLIENTARTICLESAISONIMPLSERVICE_EXCEPTION = e;
    }

    public ServiceClientArticleSaisonImplService() {
        super(__getWsdlLocation(), SERVICECLIENTARTICLESAISONIMPLSERVICE_QNAME);
    }

    public ServiceClientArticleSaisonImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SERVICECLIENTARTICLESAISONIMPLSERVICE_QNAME, features);
    }

    public ServiceClientArticleSaisonImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICECLIENTARTICLESAISONIMPLSERVICE_QNAME);
    }

    public ServiceClientArticleSaisonImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SERVICECLIENTARTICLESAISONIMPLSERVICE_QNAME, features);
    }

    public ServiceClientArticleSaisonImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ServiceClientArticleSaisonImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ServiceClientArticleSaison
     */
    @WebEndpoint(name = "ServiceClientArticleSaisonImplPort")
    public ServiceClientArticleSaison getServiceClientArticleSaisonImplPort() {
        return super.getPort(new QName("http://ws.saison.ws.citron.al33.afcepf.fr/", "ServiceClientArticleSaisonImplPort"), ServiceClientArticleSaison.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ServiceClientArticleSaison
     */
    @WebEndpoint(name = "ServiceClientArticleSaisonImplPort")
    public ServiceClientArticleSaison getServiceClientArticleSaisonImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.saison.ws.citron.al33.afcepf.fr/", "ServiceClientArticleSaisonImplPort"), ServiceClientArticleSaison.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SERVICECLIENTARTICLESAISONIMPLSERVICE_EXCEPTION!= null) {
            throw SERVICECLIENTARTICLESAISONIMPLSERVICE_EXCEPTION;
        }
        return SERVICECLIENTARTICLESAISONIMPLSERVICE_WSDL_LOCATION;
    }

}
