INSERT INTO Categorie(nom) VALUES('fruits');
INSERT INTO Categorie(nom) VALUES('légumes');
INSERT INTO Article(nom, categorie_id, debut_saison, fin_saison) VALUES('abricot', 1, 7, 8);
INSERT INTO Article(nom, categorie_id, debut_saison, fin_saison) VALUES('ail', 2, 4, 8);
INSERT INTO Article(nom, categorie_id, debut_saison, fin_saison) VALUES('ananas', 1, 11, 3);
INSERT INTO Article(nom, categorie_id, debut_saison, fin_saison) VALUES('artichaut', 2, 6, 9);
INSERT INTO Article(nom, categorie_id, debut_saison, fin_saison) VALUES('asperge blanche', 2, 4, 6);
INSERT INTO Article(nom, categorie_id, debut_saison, fin_saison) VALUES('asperge verte', 2, 5, 6);
INSERT INTO Article(nom, categorie_id, debut_saison, fin_saison) VALUES('aubergine', 2, 5, 9);
INSERT INTO Article(nom, categorie_id, debut_saison, fin_saison) VALUES('avocat', 1, 1, 12);
INSERT INTO Article(nom, categorie_id, debut_saison, fin_saison) VALUES('banane', 1, 1, 12);
INSERT INTO Article(nom, categorie_id, debut_saison, fin_saison) VALUES('betterave rouge', 2, 5, 10);
INSERT INTO Article(nom, categorie_id, debut_saison, fin_saison) VALUES('brocoli', 2, 6, 10);
INSERT INTO Article(nom, categorie_id, debut_saison, fin_saison) VALUES('carotte', 2, 1, 12);
INSERT INTO Article(nom, categorie_id, debut_saison, fin_saison) VALUES('celeri', 2, 10, 3);
INSERT INTO Article(nom, categorie_id, debut_saison, fin_saison) VALUES('celeri branche', 2, 9, 2);
INSERT INTO Article(nom, categorie_id, debut_saison, fin_saison) VALUES('celeri rave', 2, 9, 2);
INSERT INTO Article(nom, categorie_id, debut_saison, fin_saison) VALUES('cerise', 1, 6, 8);
INSERT INTO Article(nom, categorie_id, debut_saison, fin_saison) VALUES('chou blanc', 2, 1, 12);
INSERT INTO Article(nom, categorie_id, debut_saison, fin_saison) VALUES('chou de bruxelles', 2, 8, 1);
INSERT INTO Article(nom, categorie_id, debut_saison, fin_saison) VALUES('chou frise', 2, 1, 12);
INSERT INTO Article(nom, categorie_id, debut_saison, fin_saison) VALUES('chou rouge', 2, 1, 12);
INSERT INTO Article(nom, categorie_id, debut_saison, fin_saison) VALUES('chou-fleur', 2, 5, 10);
INSERT INTO Article(nom, categorie_id, debut_saison, fin_saison) VALUES('chou-rave', 2, 3, 11);
INSERT INTO Article(nom, categorie_id, debut_saison, fin_saison) VALUES('citron', 1, 1, 12);
INSERT INTO Article(nom, categorie_id, debut_saison, fin_saison) VALUES('citrouille', 2, 9, 2);
INSERT INTO Article(nom, categorie_id, debut_saison, fin_saison) VALUES('clementine', 1, 11, 2);
INSERT INTO Article(nom, categorie_id, debut_saison, fin_saison) VALUES('coing', 1, 9, 10);
INSERT INTO Article(nom, categorie_id, debut_saison, fin_saison) VALUES('concombre', 2, 5, 9);
INSERT INTO Article(nom, categorie_id, debut_saison, fin_saison) VALUES('courge', 2, 8, 12);
INSERT INTO Article(nom, categorie_id, debut_saison, fin_saison) VALUES('courgette', 2, 6, 9);
INSERT INTO Article(nom, categorie_id, debut_saison, fin_saison) VALUES('endive', 2, 11, 3);