INSERT INTO Categorie(nom) VALUES('fruits');
INSERT INTO Categorie(nom) VALUES('légumes');
INSERT INTO Article(nom, categorie_id, debut_saison, fin_saison) VALUES('abricot', 1, 7, 8);
INSERT INTO Article(nom, categorie_id, debut_saison, fin_saison) VALUES('ail', 2, 4, 8);
INSERT INTO Article(nom, categorie_id, debut_saison, fin_saison) VALUES('ananas', 1, 11, 3);
INSERT INTO Article(nom, categorie_id, debut_saison, fin_saison) VALUES('artichaut', 2, 6, 9);
INSERT INTO Article(nom, categorie_id, debut_saison, fin_saison) VALUES('asperge blanche', 2, 4, 6);
INSERT INTO Article(nom, categorie_id, debut_saison, fin_saison) VALUES('asperge verte', 2, 5, 6);
INSERT INTO Article(nom, categorie_id, debut_saison, fin_saison) VALUES('aubergine', 2, 5, 9);
INSERT INTO Article(nom, categorie_id, debut_saison, fin_saison) VALUES('avocat', 1, 1, 12);
INSERT INTO Article(nom, categorie_id, debut_saison, fin_saison) VALUES('banane', 1, 1, 12);
INSERT INTO Article(nom, categorie_id, debut_saison, fin_saison) VALUES('betterave rouge', 2, 5, 10);
INSERT INTO Article(nom, categorie_id, debut_saison, fin_saison) VALUES('brocoli', 2, 6, 10);
INSERT INTO Article(nom, categorie_id, debut_saison, fin_saison) VALUES('carotte', 2, 1, 12);
INSERT INTO Article(nom, categorie_id, debut_saison, fin_saison) VALUES('celeri', 2, 10, 3);
INSERT INTO Article(nom, categorie_id, debut_saison, fin_saison) VALUES('celeri branche', 2, 9, 2);
INSERT INTO Article(nom, categorie_id, debut_saison, fin_saison) VALUES('celeri rave', 2, 9, 2);
INSERT INTO Article(nom, categorie_id, debut_saison, fin_saison) VALUES('cerise', 1, 6, 8);
INSERT INTO Article(nom, categorie_id, debut_saison, fin_saison) VALUES('chou blanc', 2, 1, 12);
INSERT INTO Article(nom, categorie_id, debut_saison, fin_saison) VALUES('chou de bruxelles', 2, 8, 1);
INSERT INTO Article(nom, categorie_id, debut_saison, fin_saison) VALUES('chou frise', 2, 1, 12);
INSERT INTO Article(nom, categorie_id, debut_saison, fin_saison) VALUES('chou rouge', 2, 1, 12);
INSERT INTO Article(nom, categorie_id, debut_saison, fin_saison) VALUES('chou-fleur', 2, 5, 10);
INSERT INTO Article(nom, categorie_id, debut_saison, fin_saison) VALUES('chou-rave', 2, 3, 11);
INSERT INTO Article(nom, categorie_id, debut_saison, fin_saison) VALUES('citron', 1, 1, 12);
INSERT INTO Article(nom, categorie_id, debut_saison, fin_saison) VALUES('citrouille', 2, 9, 2);
INSERT INTO Article(nom, categorie_id, debut_saison, fin_saison) VALUES('clementine', 1, 11, 2);
INSERT INTO Article(nom, categorie_id, debut_saison, fin_saison) VALUES('coing', 1, 9, 10);
INSERT INTO Article(nom, categorie_id, debut_saison, fin_saison) VALUES('concombre', 2, 5, 9);
INSERT INTO Article(nom, categorie_id, debut_saison, fin_saison) VALUES('courge', 2, 8, 12);
INSERT INTO Article(nom, categorie_id, debut_saison, fin_saison) VALUES('courgette', 2, 6, 9);
INSERT INTO Article(nom, categorie_id, debut_saison, fin_saison) VALUES('endive', 2, 11, 3);
INSERT INTO Article(nom, categorie_id, debut_saison, fin_saison) VALUES('epinard', 2, 4, 11);
INSERT INTO Article(nom, categorie_id, debut_saison, fin_saison) VALUES('fenouil', 2, 5, 11);
INSERT INTO Article(nom, categorie_id, debut_saison, fin_saison) VALUES('fraise', 1, 5, 8);
INSERT INTO Article(nom, categorie_id, debut_saison, fin_saison) VALUES('framboise', 1, 6, 9);
INSERT INTO Article(nom, categorie_id, debut_saison, fin_saison) VALUES('fruit de la passion', 1, 1, 12);
INSERT INTO Article(nom, categorie_id, debut_saison, fin_saison) VALUES('grenade', 1, 11, 2);
INSERT INTO Article(nom, categorie_id, debut_saison, fin_saison) VALUES('groseille', 1, 6, 7);
INSERT INTO Article(nom, categorie_id, debut_saison, fin_saison) VALUES('haricot', 2, 6, 9);
INSERT INTO Article(nom, categorie_id, debut_saison, fin_saison) VALUES('kaki', 1, 10, 1);
INSERT INTO Article(nom, categorie_id, debut_saison, fin_saison) VALUES('kiwi', 1, 11, 5);
INSERT INTO Article(nom, categorie_id, debut_saison, fin_saison) VALUES('kumquat', 1, 11, 12);
INSERT INTO Article(nom, categorie_id, debut_saison, fin_saison) VALUES('laitue romaine', 2, 4, 10);
INSERT INTO Article(nom, categorie_id, debut_saison, fin_saison) VALUES('litchi', 1, 1, 12);
INSERT INTO Article(nom, categorie_id, debut_saison, fin_saison) VALUES('mache', 2, 11, 2);
INSERT INTO Article(nom, categorie_id, debut_saison, fin_saison) VALUES('mandarine', 1, 10, 3);
INSERT INTO Article(nom, categorie_id, debut_saison, fin_saison) VALUES('mangue', 1, 1, 12);
INSERT INTO Article(nom, categorie_id, debut_saison, fin_saison) VALUES('marron', 1, 8, 12);
INSERT INTO Article(nom, categorie_id, debut_saison, fin_saison) VALUES('melon', 2, 6, 9);
INSERT INTO Article(nom, categorie_id, debut_saison, fin_saison) VALUES('mirabelle', 1, 8, 9);
INSERT INTO Article(nom, categorie_id, debut_saison, fin_saison) VALUES('mure', 1, 7, 9);
INSERT INTO Article(nom, categorie_id, debut_saison, fin_saison) VALUES('myrtille', 1, 7, 9);
INSERT INTO Article(nom, categorie_id, debut_saison, fin_saison) VALUES('navet', 2, 6, 9);
INSERT INTO Article(nom, categorie_id, debut_saison, fin_saison) VALUES('nectarine', 1, 6, 9);
INSERT INTO Article(nom, categorie_id, debut_saison, fin_saison) VALUES('noisette', 1, 8, 10);
INSERT INTO Article(nom, categorie_id, debut_saison, fin_saison) VALUES('noix', 1, 9, 11);
INSERT INTO Article(nom, categorie_id, debut_saison, fin_saison) VALUES('oignon', 2, 8, 4);
INSERT INTO Article(nom, categorie_id, debut_saison, fin_saison) VALUES('orange', 1, 11, 2);
INSERT INTO Article(nom, categorie_id, debut_saison, fin_saison) VALUES('orange sanguine', 1, 12, 3);
INSERT INTO Article(nom, categorie_id, debut_saison, fin_saison) VALUES('pamplemousse', 1, 12, 3);
INSERT INTO Article(nom, categorie_id, debut_saison, fin_saison) VALUES('panais', 2, 9, 12);
INSERT INTO Article(nom, categorie_id, debut_saison, fin_saison) VALUES('papaye', 1, 1, 12);
INSERT INTO Article(nom, categorie_id, debut_saison, fin_saison) VALUES('pasteque', 1, 6, 9);
INSERT INTO Article(nom, categorie_id, debut_saison, fin_saison) VALUES('patisson', 2, 7, 9);
INSERT INTO Article(nom, categorie_id, debut_saison, fin_saison) VALUES('peche', 1, 6, 9);
INSERT INTO Article(nom, categorie_id, debut_saison, fin_saison) VALUES('petit oignon blanc', 2, 3, 10);
INSERT INTO Article(nom, categorie_id, debut_saison, fin_saison) VALUES('petit pois', 2, 6, 7);
INSERT INTO Article(nom, categorie_id, debut_saison, fin_saison) VALUES('poire', 1, 8, 1);
INSERT INTO Article(nom, categorie_id, debut_saison, fin_saison) VALUES('poireau', 2, 9, 3);
INSERT INTO Article(nom, categorie_id, debut_saison, fin_saison) VALUES('pois mange-tout', 2, 6, 7);
INSERT INTO Article(nom, categorie_id, debut_saison, fin_saison) VALUES('poivron', 2, 6, 10);
INSERT INTO Article(nom, categorie_id, debut_saison, fin_saison) VALUES('pomme', 1, 10, 3);
INSERT INTO Article(nom, categorie_id, debut_saison, fin_saison) VALUES('pomme de terre', 2, 1, 12);
INSERT INTO Article(nom, categorie_id, debut_saison, fin_saison) VALUES('potimarron', 2, 10, 11);
INSERT INTO Article(nom, categorie_id, debut_saison, fin_saison) VALUES('potiron', 2, 7, 10);
INSERT INTO Article(nom, categorie_id, debut_saison, fin_saison) VALUES('prune', 1, 8, 10);
INSERT INTO Article(nom, categorie_id, debut_saison, fin_saison) VALUES('quetsche', 1, 8, 10);*
INSERT INTO Article(nom, categorie_id, debut_saison, fin_saison) VALUES('radis', 2, 4, 7);
INSERT INTO Article(nom, categorie_id, debut_saison, fin_saison) VALUES('raisin', 1, 9, 10);
INSERT INTO Article(nom, categorie_id, debut_saison, fin_saison) VALUES('reine-claude', 1, 8, 9);
INSERT INTO Article(nom, categorie_id, debut_saison, fin_saison) VALUES('rhubarbe', 1, 5, 6);
INSERT INTO Article(nom, categorie_id, debut_saison, fin_saison) VALUES('salsifis', 2, 10, 3);
INSERT INTO Article(nom, categorie_id, debut_saison, fin_saison) VALUES('tomate', 2, 6, 9);
INSERT INTO Article(nom, categorie_id, debut_saison, fin_saison) VALUES('topinambour', 2, 10, 2);